import Footer from '../components/footer'
import Header from '../components/header'
import Search from '../components/search'
import '../globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function PagesLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <section>
        {children}
      </section>
  )
}
